// Einstufungstest: 40 Fragen, je 10 pro Niveau (A2, B1, B2, C1).
// Jede Frage ist einem Kursmodul (m) zugeordnet, damit falsche Antworten
// direkt als Lücke im Lernplan auftauchen.
window.PLACEMENT = [
  // ---------- A2 ----------
  { lvl: "A2", m: "m05", q: "Ich ___ gestern mit dem Zug nach München gefahren.", o: ["habe", "bin", "war", "wurde"], a: 1,
    ex: "Hareket/yer değiştirme fiilleri (fahren, gehen, kommen) Perfekt'i <b>sein</b> ile kurar." },
  { lvl: "A2", m: "m01", q: "Welcher Satz ist richtig?", o: ["Morgen ich fahre zum Kunden.", "Morgen fahre ich zum Kunden.", "Morgen zum Kunden fahre ich.", "Ich morgen fahre zum Kunden."], a: 1,
    ex: "Ana cümlede çekimli fiil her zaman <b>2. pozisyonda</b>. 'Morgen' 1. pozisyonu doldurursa özne fiilden sonra gelir." },
  { lvl: "A2", m: "m02", q: "Ich gebe ___ Kollegen den Bericht.", o: ["der", "den", "dem", "des"], a: 2,
    ex: "geben + <b>Dativ</b> (kime?) + Akkusativ (neyi?). der Kollege → dem Kollegen." },
  { lvl: "A2", m: "m02", q: "Der Ingenieur hilft ___ Praktikantin.", o: ["die", "der", "den", "das"], a: 1,
    ex: "<b>helfen</b> Dativ ister: die Praktikantin → der Praktikantin." },
  { lvl: "A2", m: "m03", q: "Ich lege das Werkzeug auf ___ Tisch.", o: ["dem", "den", "der", "das"], a: 1,
    ex: "Wechselpräposition + hareket/yön (wohin?) → <b>Akkusativ</b>: auf den Tisch." },
  { lvl: "A2", m: "m03", q: "Das Werkzeug liegt auf ___ Tisch.", o: ["dem", "den", "der", "das"], a: 0,
    ex: "Wechselpräposition + konum (wo?) → <b>Dativ</b>: auf dem Tisch." },
  { lvl: "A2", m: "m06", q: "Er kommt heute nicht, ___ er krank ist.", o: ["denn", "weil", "deshalb", "trotzdem"], a: 1,
    ex: "Fiil sonda (ist) → yan cümle bağlacı: <b>weil</b>. 'denn' ile fiil 2. pozisyonda kalırdı." },
  { lvl: "A2", m: "m04", q: "Wir haben ein ___ Auto gekauft.", o: ["neue", "neuen", "neues", "neuer"], a: 2,
    ex: "ein + nötr Akkusativ: artikel cinsiyeti göstermiyor → sıfat gösterir: ein neu<b>es</b> Auto." },
  { lvl: "A2", m: "m07", q: "Ich interessiere ___ für Aktien.", o: ["mich", "mir", "sich", "mein"], a: 0,
    ex: "sich interessieren für + Akk. Ich → <b>mich</b>." },
  { lvl: "A2", m: "m05", q: "Als Kind ___ ich in Izmir.", o: ["wohne", "wohnte", "gewohnt", "wohnen"], a: 1,
    ex: "Geçmiş zaman (Präteritum): ich wohn<b>te</b>." },

  // ---------- B1 ----------
  { lvl: "B1", m: "m07", q: "Ich warte ___ die Antwort der Bank.", o: ["auf", "für", "an", "über"], a: 0,
    ex: "warten <b>auf</b> + Akkusativ. Türkçedeki '-i beklemek' mantığıyla çevrilmez, ezberlenir." },
  { lvl: "B1", m: "m07", q: "___ wartest du? – Auf den Techniker.", o: ["Worauf", "Wofür", "Woran", "Wovon"], a: 0,
    ex: "warten auf → soru: <b>wo(r)+auf</b> = Worauf? (şeyler için; kişi için 'Auf wen?')." },
  { lvl: "B1", m: "m06", q: "Ich weiß nicht, ___ der Termin heute stattfindet.", o: ["ob", "wenn", "dass", "als"], a: 0,
    ex: "Evet/hayır belirsizliği → <b>ob</b> (-ip -mediğini)." },
  { lvl: "B1", m: "m06", q: "___ ich in Deutschland ankam, konnte ich kaum Deutsch.", o: ["Wenn", "Als", "Wann", "Ob"], a: 1,
    ex: "Geçmişte <b>tek seferlik</b> olay → <b>als</b>. Tekrarlanan veya şimdiki/gelecek → wenn." },
  { lvl: "B1", m: "m08", q: "Der Motor ___ gerade auf dem Prüfstand getestet.", o: ["wird", "ist", "hat", "war"], a: 0,
    ex: "Süreç pasifi (Vorgangspassiv): <b>werden</b> + Partizip II." },
  { lvl: "B1", m: "m10", q: "Das ist der Kollege, ___ ich gestern geholfen habe.", o: ["der", "den", "dem", "dessen"], a: 2,
    ex: "Relativpronomen'in hali yan cümledeki fiile göre: helfen + Dativ → <b>dem</b>." },
  { lvl: "B1", m: "m09", q: "Wenn ich mehr Geld ___, würde ich in ETFs investieren.", o: ["habe", "hätte", "hatte", "haben würde"], a: 1,
    ex: "Gerçek dışı koşul → Konjunktiv II: <b>hätte</b>." },
  { lvl: "B1", m: "m11", q: "Ich habe vergessen, die Datei ___ speichern.", o: ["zu", "um", "für", "—"], a: 0,
    ex: "vergessen + Infinitiv <b>mit zu</b>." },
  { lvl: "B1", m: "m11", q: "Ich spare, ___ später eine Wohnung zu kaufen.", o: ["um", "damit", "für", "dass"], a: 0,
    ex: "Amaç, iki cümlede özne aynı → <b>um … zu</b>." },
  { lvl: "B1", m: "m04", q: "Ich habe mit einem ___ Kunden gesprochen.", o: ["wichtigen", "wichtiger", "wichtigem", "wichtige"], a: 0,
    ex: "einem (Dativ) artikeli hali zaten gösteriyor → sıfat <b>-en</b>." },

  // ---------- B2 ----------
  { lvl: "B2", m: "m13", q: "Die Firma investiert ___ der hohen Kosten in die neue Anlage.", o: ["trotz", "obwohl", "trotzdem", "dennoch"], a: 0,
    ex: "İsim grubu (der hohen Kosten, Genitiv) → edat: <b>trotz</b>. obwohl yan cümle başlatır." },
  { lvl: "B2", m: "m13", q: "Der Projektleiter hat mit dem ___ gesprochen.", o: ["Kunde", "Kunden", "Kundes", "Kundem"], a: 1,
    ex: "n-Deklination: der Kunde → den/dem/des <b>Kunden</b>." },
  { lvl: "B2", m: "m12", q: "___ mehr du übst, ___ besser wird dein Deutsch.", o: ["Je – desto", "Wenn – dann", "Je – je", "Desto – je"], a: 0,
    ex: "<b>Je</b> + yan cümle (fiil sonda), <b>desto</b> + ana cümle (fiil hemen sonra)." },
  { lvl: "B2", m: "m08", q: "Das Bauteil muss bis Freitag ___ werden.", o: ["geliefert", "liefern", "geliefert worden", "zu liefern"], a: 0,
    ex: "Modalverb + Passiv: muss + Partizip II + <b>werden</b>." },
  { lvl: "B2", m: "m09", q: "Der Fehler hätte vermieden werden ___.", o: ["können", "gekonnt", "konnte", "kann"], a: 0,
    ex: "Geçmiş Konj. II + Modal + Passiv: hätte + vermieden werden + <b>können</b> (çift mastar)." },
  { lvl: "B2", m: "m12", q: "Sie spricht ___ Englisch ___ Französisch – nur Deutsch.", o: ["weder – noch", "sowohl – als auch", "entweder – oder", "nicht nur – sondern auch"], a: 0,
    ex: "İkisi de değil → <b>weder … noch</b>." },
  { lvl: "B2", m: "m10", q: "Das ist die Abteilung, ___ Leiterin morgen kommt.", o: ["deren", "dessen", "die", "der"], a: 0,
    ex: "Sahiplik + dişil öncül (die Abteilung) → <b>deren</b>." },
  { lvl: "B2", m: "m14", q: "Er wird den Termin wohl vergessen ___.", o: ["haben", "sein", "werden", "hat"], a: 0,
    ex: "Futur II = geçmişe dair tahmin: wird + Partizip II + <b>haben/sein</b>." },
  { lvl: "B2", m: "m18", q: "Das Problem ___ sich leicht lösen.", o: ["lässt", "ist", "wird", "kann"], a: 0,
    ex: "<b>sich lassen</b> + Infinitiv = 'kann gemacht werden' (Passiversatz)." },
  { lvl: "B2", m: "m11", q: "Statt den Bericht ___, hat er Kaffee getrunken.", o: ["zu schreiben", "schreiben", "geschrieben", "zu geschrieben"], a: 0,
    ex: "(an)statt … <b>zu</b> + Infinitiv." },

  // ---------- C1 ----------
  { lvl: "C1", m: "m15", q: "„Weil die Rohstoffpreise gestiegen sind, …“ = „___ der gestiegenen Rohstoffpreise …“", o: ["Aufgrund", "Obwohl", "Indem", "Damit"], a: 0,
    ex: "Nominalstil: weil → <b>aufgrund / wegen</b> + Genitiv." },
  { lvl: "C1", m: "m16", q: "Die von dem Team ___ Lösung überzeugte den Vorstand.", o: ["entwickelte", "entwickelnde", "entwickelt", "entwickelten"], a: 0,
    ex: "Pasif anlam (geliştirilmiş) → Partizip II sıfat olarak: die … entwickelt<b>e</b> Lösung." },
  { lvl: "C1", m: "m17", q: "Der Sprecher sagte, das Unternehmen ___ die Prognose bestätigt.", o: ["habe", "hat", "hätte", "haben"], a: 0,
    ex: "Dolaylı anlatım (indirekte Rede) → Konjunktiv I: er/sie/es <b>habe</b>." },
  { lvl: "C1", m: "m19", q: "Die neue Regelung tritt am 1. Januar in ___.", o: ["Kraft", "Wirkung", "Geltung", "Macht"], a: 0,
    ex: "Funktionsverbgefüge: <b>in Kraft treten</b> = yürürlüğe girmek." },
  { lvl: "C1", m: "m18", q: "„Der Antrag ist bis Ende des Monats einzureichen.“ bedeutet:", o: ["Der Antrag muss eingereicht werden.", "Der Antrag kann eingereicht werden.", "Der Antrag wurde eingereicht.", "Der Antrag wird nicht eingereicht."], a: 0,
    ex: "<b>sein + zu + Infinitiv</b> = muss/soll (bazen kann) gemacht werden." },
  { lvl: "C1", m: "m20", q: "„Er soll das Werk in China geleitet haben.“ bedeutet:", o: ["Man sagt, dass er das Werk geleitet hat.", "Er muss das Werk leiten.", "Er hatte den Auftrag, das Werk zu leiten.", "Er wollte das Werk leiten."], a: 0,
    ex: "Subjektif <b>sollen</b> = 'söylendiğine göre / iddiaya göre'." },
  { lvl: "C1", m: "m21", q: "___ die Nachfrage sinkt, erhöht der Hersteller die Produktion.", o: ["Obgleich", "Sofern", "Indem", "Sodass"], a: 0,
    ex: "Karşıtlık (-e rağmen), resmî üslup: <b>obgleich</b> = obwohl." },
  { lvl: "C1", m: "m16", q: "Die im letzten Jahr ___ Gewinne wurden reinvestiert.", o: ["erzielten", "erzielenden", "erzielt", "erzielte"], a: 0,
    ex: "Genişletilmiş Partizipialattribut: die … erzielt<b>en</b> Gewinne (çoğul, belirli artikel → -en)." },
  { lvl: "C1", m: "m15", q: "„Wir müssen die Kosten senken.“ → „Eine ___ der Kosten ist notwendig.“", o: ["Senkung", "Senken", "Gesenkte", "Sinken"], a: 0,
    ex: "senken → die <b>Senkung</b> (-ung ile isimleştirme)." },
  { lvl: "C1", m: "m09", q: "Er tut so, als ___ er alles verstanden.", o: ["hätte", "habe", "hat", "wäre"], a: 0,
    ex: "<b>als ob / als</b> + Konjunktiv II (gerçek dışı karşılaştırma). 'als' ile fiil hemen arkadan gelir." }
];
